// <auto-generated />
using System;
using DroneController.DA.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DroneController.DA.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221207033212_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DroneController.DA.Models.Drone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("battery_capacity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("model")
                        .HasColumnType("int");

                    b.Property<string>("serial_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("weight_limit")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Drones");
                });

            modelBuilder.Entity("DroneController.DA.Models.Load", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("droneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("drone_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("droneId");

                    b.ToTable("Loads");
                });

            modelBuilder.Entity("DroneController.DA.Models.Medication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LoadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("LoadId");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("DroneController.DA.Models.Load", b =>
                {
                    b.HasOne("DroneController.DA.Models.Drone", "drone")
                        .WithMany()
                        .HasForeignKey("droneId");
                });

            modelBuilder.Entity("DroneController.DA.Models.Medication", b =>
                {
                    b.HasOne("DroneController.DA.Models.Load", null)
                        .WithMany("medications")
                        .HasForeignKey("LoadId");
                });
#pragma warning restore 612, 618
        }
    }
}
